apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamdaydream-net
spec:
  selector:
    matchLabels:
      app: teamdaydream-net
  replicas: 3
  template:
    metadata:
      labels:
        app: teamdaydream-net
    spec:
      containers:
        - name: app
          image: ghcr.io/teamdaydream/teamdaydream.net:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"